# --- pyrl options ---
pyrl:
  exp_name: "hover_race" # Experiment name
  runner: "parallel" # Runs n_envs envs in parallel
  n_envs: 64 # Number of environments to run in parallel
  t_max: 120000000 # Stop running after this many timesteps
  use_cuda: True # Use gpu by default unless it isn't available

# --- Logging options ---
logging:
  use_tensorboard: True # Log results to tensorboard
  save_model: True # Save the models to disk
  save_ckpt: True # Save the checkpoints to disk
  save_config: True # Save the config file to disk
  save_model_num: 12 # The number of checkpoints to save during training
  load_model_path: None # Load a model from this path
  load_ckpt_path: None # Load a checkpoint from this path
  load_step: 0 # Load model trained on this many timesteps (0 if choose max possible)
  tb_dirname: "Learning_log" # Tensorboard logs directory
  save_model_dirname: "Learning_log" # Save the models to this path
  save_ckpt_dirname: "Learning_log" # Save the checkpoints to this path
  save_config_dirname: "Learning_log" # Save the config file to this path
  save_model_name: "PPO" # The name of the model to save
  log_interval: 1 # Log every n steps
  progress_bar: True # Show progress bar
  reset_num_timesteps: True # Reset the number of timesteps