# settings for visualizing a single waypoint
track_file: race_uzh_19g

2d_kwargs:
  dpi: 300
  cmap: cool_r

3d_kwargs:
  dpi: 300
  shade: True
  cmap: cool_r

# ani config
ani_kwargs:
  fps: 30
  dpi: 200
  traj_history: 0.0
  follow_drone: False
  hide_background: False
  hide_ground: False
  # flash_gate: False
  cmap: cool_r

# show the drone
drone_kargs:
  draw_level: 1
  show_body_axis: True
  # arm_length: 0.2
  # arm_angle: 3.1415926 * 65 / 180
  quad_type: X
  arm_color: black
  front_color: chartreuse
  back_color: deepskyblue
  body_top_color: gray
  body_side_color: black
  body_edge_color: white
  body_alpha: 0.5

# waypoint shape
shape_kwargs:
  radius: 1.0
  margin: 0.5

# waypoint color
gate_kwargs:
  gate_color: darkblue
  gate_alpha: 0.15